[pytest]

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

addopts = --alluredir=allure-results --clean-alluredir

markers =
    smoke: Smoke test cases
    regression: Regression test cases
    login: Login test cases
    dashboard: Dashboard test cases
    pim: PIM test cases
    employee: Employee test cases
    leave: Leave test cases
    recruitment: Recruitment test cases
    admin: Admin test cases